// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace AuthenticationService.Web.Contexts.Entities.Compiled
{
    [DbContext(typeof(UserContext))]
    public partial class UserContextModel : RuntimeModel
    {
        static UserContextModel()
        {
            var model = new UserContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static UserContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
