// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace AuthenticationService.Web.Contexts.Entities.Compiled
{
    public partial class UserContextModel
    {
        partial void Initialize()
        {
            var tokenEntity = TokenEntityEntityType.Create(this);
            var userEntity = UserEntityEntityType.Create(this);

            UserEntityEntityType.CreateForeignKey1(userEntity, tokenEntity);

            TokenEntityEntityType.CreateAnnotations(tokenEntity);
            UserEntityEntityType.CreateAnnotations(userEntity);

            AddAnnotation("ProductVersion", "6.0.5");
        }
    }
}
