version: '3.9'
services:
  service-aggregator-microservice:
    container_name: auth 
    build: 
      context: ./
      dockerfile: ./auth/Dockerfile
    ports:
      - 5050:5050
      - 8080:8080
    networks:
      - services
      - default

networks:
  services:
    name: 'services_network'