version: '3.9'
services:
  work-it-server:
    container_name: server
    build: ./client
    network_mode: "host"
    ports:
      - 443:443
      - 80:80
  authentication-proxy:
    container_name: proxy
    build: ./auth-proxy
    ports:
      - 3000:3000
    depends_on:
      - redis_proxy
      - work-it-server
    volumes:
      - ./auth-proxy/server_config.production.toml:/auth-proxy/src/server_config.toml
    environment:
      - DB_HOST=db.auth.proxy
  redis_proxy:
    container_name: db.auth.proxy
    image: redis:6.2.6-alpine
  service-aggregator-microservice:
    container_name: aggregator 
    build: 
      context: ./
      dockerfile: ./aggregator/Dockerfile
    ports:
      - 4500:4500
    depends_on:
      - mongodb
  mongodb:
    container_name: db.aggregator
    image: mongo
  authentication-microservice:
    container_name: auth 
    build: 
      context: ./
      dockerfile: ./auth/Dockerfile
    depends_on:
      - service-aggregator-microservice
    ports:
      - 5050:5050
      - 8080:8080
  training-service-microservice:
    container_name: training_service_microservice
    build: 
      context: ./
      dockerfile: ./fitness/training-service/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres_fitness_dimension
      - service-aggregator-microservice
  routine-service-microservice:
    container_name: routine_service_microservice
    build: 
      context: ./fitness/routine-service/
    ports:
      - "3550:3000"
    depends_on:
      - postgres_fitness_dimension
      - service-aggregator-microservice
  postgres_fitness_dimension:
    container_name: db.fitness.dimension
    build: './fitness/db'
    ports:
      - "5432:5432"
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./fitness/db/sql/work-it-db.sql:/docker-entrypoint-initdb.d/work-it-db.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=WorkItDB
  social-dimension-microservice:
    container_name: social_dimension_microservice
    build: 
      context: ./
      dockerfile: ./social/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres_social_dimension
      - service-aggregator-microservice
    volumes:
      - ./social/src/main/resources/application.prod.conf:/workit-social-dimension-microservice/social/src/main/resources/application.conf
  postgres_social_dimension:
    container_name: db.social.dimension
    build: './social/db'
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - "5433:5432"
    volumes:
      - ./social/db/sql/work-it-db.sql:/docker-entrypoint-initdb.d/work-it-db.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=work-it
