version: '3.9'
services:
  fitness-dimension-microservice:
    container_name: fitness_dimension_microservice
    build: './fitness-dimension'
    ports:
      - "8080:8080"
    depends_on:
      - postgres_fitness_dimension
    networks:
      - services
      - default
  postgres_fitness_dimension:
    container_name: db.fitness.dimension
    build: './fitness-dimension/db'
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./fitness-dimension/db/sql/work-it-db.sql:/docker-entrypoint-initdb.d/work-it-db.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=WorkItDB

networks:
  services:
    name: 'services_network'