version: '3.9'
services:
  training-service-microservice:
    container_name: training_service_microservice
    build: 
      context: ./
      dockerfile: ./fitness/training-service/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres_training_service
    networks:
      - services
      - default
  postgres_training_service:
    container_name: db.fitness.dimension
    build: './fitness/training-service/pkg/db'
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./fitness/training-service/pkg/db/sql/work-it-db.sql:/docker-entrypoint-initdb.d/work-it-db.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=WorkItDB

networks:
  services:
    name: 'services_network'
