// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: fitness.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TrainingCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Categories  []string `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	TrainerId   string   `protobuf:"bytes,3,opt,name=trainerId,proto3" json:"trainerId,omitempty"`
	Name        string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	VideoId     string   `protobuf:"bytes,6,opt,name=videoId,proto3" json:"videoId,omitempty"`
}

func (x *TrainingCreated) Reset() {
	*x = TrainingCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingCreated) ProtoMessage() {}

func (x *TrainingCreated) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingCreated.ProtoReflect.Descriptor instead.
func (*TrainingCreated) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{1}
}

func (x *TrainingCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingCreated) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *TrainingCreated) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *TrainingCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingCreated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TrainingCreated) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type TrainingUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Categories  []string `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	TrainerId   string   `protobuf:"bytes,3,opt,name=trainerId,proto3" json:"trainerId,omitempty"`
	Name        string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *TrainingUpdated) Reset() {
	*x = TrainingUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingUpdated) ProtoMessage() {}

func (x *TrainingUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingUpdated.ProtoReflect.Descriptor instead.
func (*TrainingUpdated) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{2}
}

func (x *TrainingUpdated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingUpdated) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *TrainingUpdated) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *TrainingUpdated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingUpdated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TrainingDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TrainingDeleted) Reset() {
	*x = TrainingDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingDeleted) ProtoMessage() {}

func (x *TrainingDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingDeleted.ProtoReflect.Descriptor instead.
func (*TrainingDeleted) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{3}
}

func (x *TrainingDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TrainingVideoCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TrainingId string `protobuf:"bytes,2,opt,name=trainingId,proto3" json:"trainingId,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Ext        string `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
	Video      []byte `protobuf:"bytes,5,opt,name=video,proto3" json:"video,omitempty"`
}

func (x *TrainingVideoCreated) Reset() {
	*x = TrainingVideoCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingVideoCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingVideoCreated) ProtoMessage() {}

func (x *TrainingVideoCreated) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingVideoCreated.ProtoReflect.Descriptor instead.
func (*TrainingVideoCreated) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{4}
}

func (x *TrainingVideoCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingVideoCreated) GetTrainingId() string {
	if x != nil {
		return x.TrainingId
	}
	return ""
}

func (x *TrainingVideoCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingVideoCreated) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *TrainingVideoCreated) GetVideo() []byte {
	if x != nil {
		return x.Video
	}
	return nil
}

type TrainingVideoDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TrainingVideoDeleted) Reset() {
	*x = TrainingVideoDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingVideoDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingVideoDeleted) ProtoMessage() {}

func (x *TrainingVideoDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingVideoDeleted.ProtoReflect.Descriptor instead.
func (*TrainingVideoDeleted) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{5}
}

func (x *TrainingVideoDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TrainerDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TrainerDeleted) Reset() {
	*x = TrainerDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainerDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainerDeleted) ProtoMessage() {}

func (x *TrainerDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainerDeleted.ProtoReflect.Descriptor instead.
func (*TrainerDeleted) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{6}
}

func (x *TrainerDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RoutineCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId      string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Description string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TrainingsId []string `protobuf:"bytes,5,rep,name=trainingsId,proto3" json:"trainingsId,omitempty"`
}

func (x *RoutineCreated) Reset() {
	*x = RoutineCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineCreated) ProtoMessage() {}

func (x *RoutineCreated) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineCreated.ProtoReflect.Descriptor instead.
func (*RoutineCreated) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{7}
}

func (x *RoutineCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoutineCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoutineCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoutineCreated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoutineCreated) GetTrainingsId() []string {
	if x != nil {
		return x.TrainingsId
	}
	return nil
}

type RoutineUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId      string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Description string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TrainingsId []string `protobuf:"bytes,5,rep,name=trainingsId,proto3" json:"trainingsId,omitempty"`
}

func (x *RoutineUpdated) Reset() {
	*x = RoutineUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineUpdated) ProtoMessage() {}

func (x *RoutineUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineUpdated.ProtoReflect.Descriptor instead.
func (*RoutineUpdated) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{8}
}

func (x *RoutineUpdated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoutineUpdated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoutineUpdated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoutineUpdated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoutineUpdated) GetTrainingsId() []string {
	if x != nil {
		return x.TrainingsId
	}
	return nil
}

type RoutineDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RoutineDeleted) Reset() {
	*x = RoutineDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineDeleted) ProtoMessage() {}

func (x *RoutineDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineDeleted.ProtoReflect.Descriptor instead.
func (*RoutineDeleted) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{9}
}

func (x *RoutineDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TrainingAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutineId  string `protobuf:"bytes,1,opt,name=routineId,proto3" json:"routineId,omitempty"`
	TrainingId string `protobuf:"bytes,2,opt,name=trainingId,proto3" json:"trainingId,omitempty"`
	Order      int32  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *TrainingAdded) Reset() {
	*x = TrainingAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingAdded) ProtoMessage() {}

func (x *TrainingAdded) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingAdded.ProtoReflect.Descriptor instead.
func (*TrainingAdded) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{10}
}

func (x *TrainingAdded) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *TrainingAdded) GetTrainingId() string {
	if x != nil {
		return x.TrainingId
	}
	return ""
}

func (x *TrainingAdded) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type TrainingRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutineId  string `protobuf:"bytes,1,opt,name=routineId,proto3" json:"routineId,omitempty"`
	TrainingId string `protobuf:"bytes,2,opt,name=trainingId,proto3" json:"trainingId,omitempty"`
}

func (x *TrainingRemoved) Reset() {
	*x = TrainingRemoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingRemoved) ProtoMessage() {}

func (x *TrainingRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingRemoved.ProtoReflect.Descriptor instead.
func (*TrainingRemoved) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{11}
}

func (x *TrainingRemoved) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *TrainingRemoved) GetTrainingId() string {
	if x != nil {
		return x.TrainingId
	}
	return ""
}

type ParticipantDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ParticipantDeleted) Reset() {
	*x = ParticipantDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParticipantDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantDeleted) ProtoMessage() {}

func (x *ParticipantDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantDeleted.ProtoReflect.Descriptor instead.
func (*ParticipantDeleted) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{12}
}

func (x *ParticipantDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ParticipantChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldId string `protobuf:"bytes,1,opt,name=oldId,proto3" json:"oldId,omitempty"`
	NewId string `protobuf:"bytes,2,opt,name=newId,proto3" json:"newId,omitempty"`
}

func (x *ParticipantChanged) Reset() {
	*x = ParticipantChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParticipantChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantChanged) ProtoMessage() {}

func (x *ParticipantChanged) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantChanged.ProtoReflect.Descriptor instead.
func (*ParticipantChanged) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{13}
}

func (x *ParticipantChanged) GetOldId() string {
	if x != nil {
		return x.OldId
	}
	return ""
}

func (x *ParticipantChanged) GetNewId() string {
	if x != nil {
		return x.NewId
	}
	return ""
}

type SummaryCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoutineId string `protobuf:"bytes,2,opt,name=routineId,proto3" json:"routineId,omitempty"`
}

func (x *SummaryCreated) Reset() {
	*x = SummaryCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryCreated) ProtoMessage() {}

func (x *SummaryCreated) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryCreated.ProtoReflect.Descriptor instead.
func (*SummaryCreated) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{14}
}

func (x *SummaryCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SummaryCreated) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

type SummaryUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutineId string `protobuf:"bytes,1,opt,name=routineId,proto3" json:"routineId,omitempty"`
	Mintime   string `protobuf:"bytes,2,opt,name=mintime,proto3" json:"mintime,omitempty"`
	Maxtime   string `protobuf:"bytes,3,opt,name=maxtime,proto3" json:"maxtime,omitempty"`
}

func (x *SummaryUpdated) Reset() {
	*x = SummaryUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fitness_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryUpdated) ProtoMessage() {}

func (x *SummaryUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_fitness_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryUpdated.ProtoReflect.Descriptor instead.
func (*SummaryUpdated) Descriptor() ([]byte, []int) {
	return file_fitness_proto_rawDescGZIP(), []int{15}
}

func (x *SummaryUpdated) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *SummaryUpdated) GetMintime() string {
	if x != nil {
		return x.Mintime
	}
	return ""
}

func (x *SummaryUpdated) GetMaxtime() string {
	if x != nil {
		return x.Maxtime
	}
	return ""
}

var File_fitness_proto protoreflect.FileDescriptor

var file_fitness_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x1c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0xaf, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x21, 0x0a,
	0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x82, 0x01, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x26, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a,
	0x0e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x90, 0x01, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x73,
	0x49, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x73,
	0x49, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x73, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x63, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x4f, 0x0a, 0x0f,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x24, 0x0a,
	0x12, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x6c, 0x64,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x6c, 0x64, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x65, 0x77, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6e, 0x65, 0x77, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x0e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x61, 0x78, 0x74, 0x69, 0x6d, 0x65, 0x32, 0xd7, 0x02, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x41, 0x50, 0x49, 0x12, 0x2f, 0x0a, 0x04, 0x53, 0x61, 0x76,
	0x65, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x1a, 0x0e,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x39, 0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1a, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1a, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x79, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x32, 0x95, 0x03, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x41,
	0x50, 0x49, 0x12, 0x2e, 0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x14, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x30, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x14,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x15,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x79, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x12, 0x18,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x11, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x12,
	0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x6e, 0x0a, 0x0a, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x41, 0x50, 0x49, 0x12, 0x2e, 0x0a, 0x04, 0x53, 0x61, 0x76,
	0x65, 0x12, 0x14, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x0a, 0x18, 0x75,
	0x63, 0x61, 0x62, 0x2e, 0x73, 0x71, 0x61, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x62, 0x6f, 0x62, 0x75, 0x66, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fitness_proto_rawDescOnce sync.Once
	file_fitness_proto_rawDescData = file_fitness_proto_rawDesc
)

func file_fitness_proto_rawDescGZIP() []byte {
	file_fitness_proto_rawDescOnce.Do(func() {
		file_fitness_proto_rawDescData = protoimpl.X.CompressGZIP(file_fitness_proto_rawDescData)
	})
	return file_fitness_proto_rawDescData
}

var file_fitness_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_fitness_proto_goTypes = []interface{}{
	(*Response)(nil),             // 0: main.Response
	(*TrainingCreated)(nil),      // 1: main.TrainingCreated
	(*TrainingUpdated)(nil),      // 2: main.TrainingUpdated
	(*TrainingDeleted)(nil),      // 3: main.TrainingDeleted
	(*TrainingVideoCreated)(nil), // 4: main.TrainingVideoCreated
	(*TrainingVideoDeleted)(nil), // 5: main.TrainingVideoDeleted
	(*TrainerDeleted)(nil),       // 6: main.TrainerDeleted
	(*RoutineCreated)(nil),       // 7: main.RoutineCreated
	(*RoutineUpdated)(nil),       // 8: main.RoutineUpdated
	(*RoutineDeleted)(nil),       // 9: main.RoutineDeleted
	(*TrainingAdded)(nil),        // 10: main.TrainingAdded
	(*TrainingRemoved)(nil),      // 11: main.TrainingRemoved
	(*ParticipantDeleted)(nil),   // 12: main.ParticipantDeleted
	(*ParticipantChanged)(nil),   // 13: main.ParticipantChanged
	(*SummaryCreated)(nil),       // 14: main.SummaryCreated
	(*SummaryUpdated)(nil),       // 15: main.SummaryUpdated
}
var file_fitness_proto_depIdxs = []int32{
	1,  // 0: main.trainingAPI.Save:input_type -> main.TrainingCreated
	2,  // 1: main.trainingAPI.Update:input_type -> main.TrainingUpdated
	3,  // 2: main.trainingAPI.Delete:input_type -> main.TrainingDeleted
	4,  // 3: main.trainingAPI.SaveVideo:input_type -> main.TrainingVideoCreated
	5,  // 4: main.trainingAPI.DeleteVideo:input_type -> main.TrainingVideoDeleted
	6,  // 5: main.trainingAPI.DeleteByTrainer:input_type -> main.TrainerDeleted
	7,  // 6: main.routineAPI.Save:input_type -> main.RoutineCreated
	8,  // 7: main.routineAPI.Update:input_type -> main.RoutineUpdated
	9,  // 8: main.routineAPI.Delete:input_type -> main.RoutineDeleted
	10, // 9: main.routineAPI.AddTraining:input_type -> main.TrainingAdded
	11, // 10: main.routineAPI.RemoveTraining:input_type -> main.TrainingRemoved
	12, // 11: main.routineAPI.DeleteByParticipant:input_type -> main.ParticipantDeleted
	13, // 12: main.routineAPI.ChangeParticipant:input_type -> main.ParticipantChanged
	14, // 13: main.summaryAPI.Save:input_type -> main.SummaryCreated
	15, // 14: main.summaryAPI.Update:input_type -> main.SummaryUpdated
	0,  // 15: main.trainingAPI.Save:output_type -> main.Response
	0,  // 16: main.trainingAPI.Update:output_type -> main.Response
	0,  // 17: main.trainingAPI.Delete:output_type -> main.Response
	0,  // 18: main.trainingAPI.SaveVideo:output_type -> main.Response
	0,  // 19: main.trainingAPI.DeleteVideo:output_type -> main.Response
	0,  // 20: main.trainingAPI.DeleteByTrainer:output_type -> main.Response
	0,  // 21: main.routineAPI.Save:output_type -> main.Response
	0,  // 22: main.routineAPI.Update:output_type -> main.Response
	0,  // 23: main.routineAPI.Delete:output_type -> main.Response
	0,  // 24: main.routineAPI.AddTraining:output_type -> main.Response
	0,  // 25: main.routineAPI.RemoveTraining:output_type -> main.Response
	0,  // 26: main.routineAPI.DeleteByParticipant:output_type -> main.Response
	0,  // 27: main.routineAPI.ChangeParticipant:output_type -> main.Response
	0,  // 28: main.summaryAPI.Save:output_type -> main.Response
	0,  // 29: main.summaryAPI.Update:output_type -> main.Response
	15, // [15:30] is the sub-list for method output_type
	0,  // [0:15] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fitness_proto_init() }
func file_fitness_proto_init() {
	if File_fitness_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fitness_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingVideoCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingVideoDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainerDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingRemoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParticipantDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParticipantChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummaryCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fitness_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummaryUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fitness_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_fitness_proto_goTypes,
		DependencyIndexes: file_fitness_proto_depIdxs,
		MessageInfos:      file_fitness_proto_msgTypes,
	}.Build()
	File_fitness_proto = out.File
	file_fitness_proto_rawDesc = nil
	file_fitness_proto_goTypes = nil
	file_fitness_proto_depIdxs = nil
}
