// <auto-generated />
using System;
using AuthenticationService.Web.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthenticationService.Web.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20220904163019_AddedPrimaryKeyToToken")]
    partial class AddedPrimaryKeyToToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("AuthenticationService.Web.Contexts.Entities.TokenEntity", b =>
                {
                    b.Property<string>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ExpiresIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId");

                    b.HasIndex("Hash");

                    b.HasIndex("Id");

                    b.ToTable("work-it-tokens");
                });

            modelBuilder.Entity("AuthenticationService.Web.Contexts.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenOwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenOwnerId");

                    b.ToTable("work-it-users");
                });

            modelBuilder.Entity("AuthenticationService.Web.Contexts.Entities.UserEntity", b =>
                {
                    b.HasOne("AuthenticationService.Web.Contexts.Entities.TokenEntity", "Token")
                        .WithMany()
                        .HasForeignKey("TokenOwnerId");

                    b.Navigation("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
