authority = "auth"

[servers.auth]
from = "/api/auth"
to = "http://localhost:5050"

[servers.social]
from = "/api/social"
to = "http://localhost:5000"

[servers.trainings]
from = "/api/trainings"
to = "http://localhost:8080"

[servers.routines]
from = "/api/routines"
to = "http://localhost:3550"

[servers.reports]
from = "/api/reports"
to = "http://localhost:3500"

[servers.summary]
from = "/api/summary"
to = "http://localhost:8081"
