authority = "auth"

[servers.auth]
from = "/api/auth"
to = "http://auth:5050"

[servers.social]
from = "/api/social"
to = "http://social_dimension_microservice:5000"

[servers.fitness]
from = "/api/fitness"
to = "http://fitness_dimension_microservice:8080"
