authority = "auth"

[servers.auth]
from = "/api/auth"
to = "http://auth:5050"

[servers.social]
from = "/api/social"
to = "http://social_dimension_microservice:5000"

[servers.trainings]
from = "/api/trainings"
to = "http://training_service_microservice:8080"

[servers.routines]
from = "/api/routines"
to = "http://routine_service_microservice:3550"
