authority = "auth"

[servers.auth]
from = "/api/auth"
to = "http://172.17.0.1:5050"

[servers.social]
from = "/api/social"
to = "http://172.17.0.1:5000"

[servers.trainings]
from = "/api/trainings"
to = "http://172.17.0.1:8082"

[servers.routines]
from = "/api/routines"
to = "http://172.17.0.1:3550"
